# All Docker images used for Continuous Integration should extend from this
# image. Currently it's no different than dimo414/base but some of that image's
# behavior may be moved down to this one.

FROM dimo414/base

LABEL \
  version="0.1" \
  description="Base image for BitBucket Continuous Integration. \
  Most projects will be able to use this directly."
