# hadolint ignore=DL3006
FROM dimo414/base

LABEL \
  version="0.1" \
  description="Base image for Continuous Integration tasks, such as GitHub actions. \
  Most projects will be able to use this directly."
