name: Build

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Name of the package / directory to build'
        required: true
        type: choice
        options:
          - openscad
          - utf8
      tag:
        description: 'Package tag'
        required: false
        default: 'latest'
        type: string


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker ${{ inputs.package }} image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ inputs.package }} "
          tags: ghcr.io/dimo414/${{ inputs.package }}:${{ inputs.tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/dimo414/docker/tree/master/${{ inputs.package }}
            org.opencontainers.image.vendor=dimo414
          push: true
