name: Build

on: [workflow_dispatch]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:openscad"
          tags: ghcr.io/dimo414/openscad:latest
          labels: |
            org.opencontainers.image.title=OpenSCAD
            org.opencontainers.image.source=https://github.com/dimo414/docker/tree/master/openscad
            org.opencontainers.image.vendor=dimo414
          push: true
