name: CI

on: [push]

jobs:
  # https://stackoverflow.com/q/28182047/113632
  hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint

    steps:
    - uses: actions/checkout@v1
    - name: hadolint
      # DL3008 - don't pin versions in apt-get
      # DL4006 - don't use set -o pipefail
      run: sh -c 'hadolint --ignore DL3008 --ignore DL4006 */Dockerfile'
